[package]
name = "cocktail-init"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rand_core = { workspace = true, features = ["getrandom"] }
reqwest = { workspace = true }
futures-util.workspace = true
cocktail-shared = { path = "../cocktail-shared" }
zip = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

[target.'cfg(windows)'.dependencies]
reqwest = { workspace = true, features = ["native-tls"] }

[dev-dependencies]
tempfile = "3"
uuid = { workspace = true }

[lib]
name = "cocktail_init"
path = "src/lib.rs"

[[bin]]
name = "cocktail-init"
path = "src/main.rs"
