<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Cocktail.Plugins.Watchdog</RootNamespace>
    <AssemblyName>Cocktail.Plugins.Watchdog</AssemblyName>
    <PluginId>watchdog</PluginId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Cocktail.Sdk\Cocktail.Sdk.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="plugin.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <Import Project="..\PluginPack.targets" />
</Project>
